name: Publish to npm

on:
  workflow_run:
    workflows:
      - 'Tests'
    types:
      - completed

  pull_request:
    branches:
      - main
    types:
      - closed
    tags:
      - 'v*'

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
