name: Publish
on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Get package version
        id: package-version
        run: echo "current-version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Publish stable
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --provenance --access public --tag ${{ steps.package-version.outputs.current-version || 'latest' }}
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
